server:
    port: 80

spring:
    application:
      name: Spring-boot
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
#mybatis:
  #mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.gome.wp.model
  #executor-type: SIMPLE